# Generated by Django 5.1.6 on 2025-03-04 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=128)),
                ("state", models.CharField(max_length=128)),
                ("country", models.CharField(max_length=32)),
                ("zip_code", models.CharField(max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("description", models.TextField()),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("AP", "Apartment"),
                            ("HO", "House"),
                            ("CO", "Condo"),
                            ("LA", "Land"),
                        ],
                        max_length=20,
                    ),
                ),
                ("square_feet", models.PositiveIntegerField()),
                ("bedrooms", models.PositiveSmallIntegerField()),
                ("bathrooms", models.PositiveSmallIntegerField()),
                ("has_garage", models.BooleanField(default=False)),
                ("has_balcony", models.BooleanField(default=False)),
                ("has_basement", models.BooleanField(default=False)),
                ("has_pool", models.BooleanField(default=False)),
                ("year_built", models.PositiveIntegerField(blank=True, null=True)),
                ("is_available", models.BooleanField(default=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="estates.location",
                    ),
                ),
            ],
        ),
    ]
